nrmay/TeSS

- Gemfile
- app/views/static/home.html.erb
- config/unicorn.rb
- unicorn_tess
> Branding: add unicorn files.

- Gemfile
- README.md
- app/assets/javascripts/handlebars_helpers.js
- app/assets/javascripts/term_suggestions.js
- app/assets/javascripts/workflows.js
- app/dictionaries/dictionary.rb
- app/dictionaries/difficulty_dictionary.rb
- app/dictionaries/eligibility_dictionary.rb
- app/dictionaries/event_type_dictionary.rb
- app/helpers/search_helper.rb
- app/models/event.rb
- app/views/content_providers/_form.html.erb
- app/views/events/_form.html.erb
- app/views/events/partials/_address_finder.html.erb
- app/views/events/show.html.erb
- app/views/materials/_form.html.erb
- config/dictionaries/difficulty_dresa.yml
- config/dictionaries/eligibility_dresa.yml
- config/dictionaries/event_types_dresa.yml
- config/tess.example.yml
- db/migrate/20210519054952_add_fields_to_events.rb
- db/schema.rb
- test/config/test_tess.yml
- test/controllers/curator_controller_test.rb
- test/controllers/events_controller_test.rb
- test/fixtures/events.yml
- test/models/event_test.rb
- test/unit/dictionaries_test.rb
- test/unit/licence_dictionary_test.rb
Various formatting and code layout fixes.
> Code quality

- Gemfile
- Gemfile.lock
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/_form.html.erb
- test/controllers/events_controller_test.rb
- test/fixtures/events.yml
Migration 5.2
Added four three fields to events.
Changed timezone screen format.
> Feature mapping

- README.md
- scripts/pgsql_backup.sh
- scripts/pgsql_restore.sh
- update_production.sh
- update_tess.sh
Add scripts and readme instructions for backup and restore.
> Backup restore

- config/locales/rails_admin.en-AU.yml
- config/locales/rails_admin.en-EU.yml
Fix missing translations on admin UI.
> Fix missing translations for the admin UI.

- app/views/static/privacy.html.erb
- config/locales/en-AU.yml
- update_tess.sh
Update section title in Privacy page.
Fix Working Group names.
> Some UI fixes.

- app/models/user.rb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/_header.html.erb
- config/tess.example.yml
- test/config/test_tess.yml
Add switch to show/hide registration.
> Rego disable

- app/views/events/show.html.erb
- app/views/users/show.html.erb
- config/tess.example.yml
Fix UI server 500 errors on show event and user.
> Fix bugs in master: missing registration path, invalid cost_basis.

- app/views/common/_default_og.html.erb
- app/views/elearning_materials/partials/_twitter_card.html.erb
- app/views/events/partials/_twitter_card.html.erb
- app/views/materials/partials/_twitter_card.html.erb
- config/tess.example.yml
Add to tess.yml: 
default.twitter_handle: '@DReSA_news'
> updated twitter cards and og tags.

- app/views/events/partials/_address_finder.html.erb
Format the address fields (venue, city, country, postcode) correctly when location selected in the address field.
> Bug 75 address fields

- app/views/layouts/_dresa_funded_by.erb
- app/views/layouts/_footer.html.erb
> Progressively hide footer content on small screens. 

- app/views/layouts/_header.html.erb
Fix truncation of application name in top header.
> Update top header layout.

- app/assets/stylesheets/application.scss
- app/views/layouts/_footer.html.erb
- top header: server name truncation.
- footer: overlapping body as rows wrap.
- footer: supported by icons wrapping.
> Fix layout issues on resizing.

- app/assets/stylesheets/application.scss
> Fix card length bug.

- app/models/material.rb
- test/controllers/materials_controller_test.rb
> Added subsets to clean array fields.

- app/views/users/show.html.erb
> Updated feature checks and added packages to user page.

- config/sitemap.rb
> Fix sitemap failing on disabled features.

- app/views/events/show.html.erb
> fixed activity log tab.

- app/views/common/_extra_metadata.html.erb
- app/views/materials/_form.html.erb
> Materials: fixed displays of dictionaries (show) and field labels (new).

- app/views/content_providers/show.html.erb
- app/views/events/show.html.erb
- app/views/layouts/_google_analytics.html.erb
- app/views/materials/show.html.erb
> 137 capture outbound links

- app/models/concerns/searchable.rb
- app/models/subscription.rb
- config/environments/development.rb
- config/environments/production.rb
- config/tess.example.yml
- lib/tasks/tess.rake
- test/config/test_tess.yml
> 132 convert to postfix

- CHANGE_LOG.md
> Add email related fixes.

- config/schedule.rb
- update_production.sh
Added db backup to schedule.rb
> Added backup command to schedule.

- config/logrotate.conf
- config/schedule.example.yml
- config/schedule.rb
- lib/tasks/tess.rake
- update_production.sh
- update_tess.sh
Added configuration file for the timings of scheduled jobs.
Added logrotate job and configuration file.
Added logrotate service restart to update scripts.
> 145 backend services

- Gemfile.lock
- app/controllers/events_controller.rb
- app/policies/event_policy.rb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- config/routes.rb
Enable cloning of events from details page.
> Add clone event action.

- .circleci/config.yml
- .rubocop.yml
- Gemfile.lock
- config/environments/test.rb
- config/ingestion.example.yml
- config/schedule.example.yml
- config/schedule.rb
- lib/ingestors/ingestor.rb
- lib/ingestors/ingestor_event.rb
- lib/ingestors/ingestor_event_csv.rb
- lib/ingestors/ingestor_factory.rb
- lib/ingestors/ingestor_material.rb
- lib/ingestors/ingestor_material_csv.rb
- lib/scraper.rb
- lib/tasks/tess.rake
- test/config/test_ingestion.yml
- test/config/test_ingestion_bad.yml
- test/config/test_ingestion_example.yml
- test/config/test_tess.yml
- test/fixtures/files/events.csv
- test/fixtures/files/materials.csv
- test/tasks/rake_task_automated_ingestion.rb
- test/tasks/rake_task_event_ingestion.rb
- test/tasks/rake_task_material_ingestion.rb
- test/test_helper.rb
> Add generic ingestion framework.

- lib/ingestors/ingestor_event_rest.rb
- test/tasks/rake_task_event_rest.rb
- test/test_helper.rb
Update eventbrite ingestion query.
> Refactor eventbrite event ingestor.

- app/views/devise/mailer/invitation_instructions.html.erb
- app/views/devise/mailer/invitation_instructions.text.erb
- config/locales/devise.en-AU.yml
- config/locales/devise.en.yml
* Bump Sidekiq version.
* Added more information text to html
Co-authored-by: eResEngineer <nmay@walroz.org>
> 374 invite email (#59)

- CHANGE_LOG.md
- app/models/content_provider.rb
- app/models/event.rb
- app/models/material.rb
- app/models/package.rb
- app/models/trainer.rb
- app/views/events/_form.html.erb
- config/tess.example.yml
* Updates to packages, content_providers, and trainers.
* Updated all models.
* Updated event and material search and filter options.
* Fix trainer filters.
* Fixed language filter as label.
Co-authored-by: Nick May <nrmay@users.noreply.github.com>
Co-authored-by: Nick @ Archer <nmay@walroz.org>
> 321 optimize search fields (#60)
